naturelist = [
	{ nature: 'Adamant', str: 'atk', weakness: 'sp.atk'},
	{ nature: 'Brave', str: 'atk', weakness: 'spe'},
	{ nature: 'Lonely', str: 'atk', weakness: 'def'},
	{ nature: 'Naughty', str: 'atk', weakness: 'sp.def'},
	{ nature: 'Bold', str: 'def', weakness: 'atk'},
	{ nature: 'Relaxed', str: 'def', weakness: 'spe'},
	{ nature: 'Impish', str: 'def', weakness: 'sp.atk'},
	{ nature: 'Lax', str: 'def', weakness: 'sp.def'},
	{ nature: 'Timid', str: 'spe', weakness: 'atk'},
	{ nature: 'Hasty', str: 'spe', weakness: 'def'},
	{ nature: 'Jolly', str: 'spe', weakness: 'sp.atk'},
	{ nature: 'Naive', str: 'spe', weakness: 'sp.def'},
	{ nature: 'Modest', str: 'sp.atk', weakness: 'atk'},
	{ nature: 'Mild', str: 'sp.atk', weakness: 'def'},
	{ nature: 'Quiet', str: 'sp.atk', weakness: 'spe'},
	{ nature: 'Rash', str: 'sp.atk', weakness: 'sp.def'},
	{ nature: 'Calm', str: 'sp.def', weakness: 'atk'},
	{ nature: 'Gentle', str: 'sp.def', weakness: 'def'},
	{ nature: 'Sassy', str: 'sp.def', weakness: 'spe'},
	{ nature: 'Careful', str: 'sp.def', weakness: 'sp.atk'},
	{ nature: 'Hardy', str: '', weakness: ''},
	{ nature: 'Docile', str: '', weakness: ''},
	{ nature: 'Serious', str: '', weakness: ''},
	{ nature: 'Bashful', str: '', weakness: ''},
	{ nature: 'Quirky', str: '', weakness: ''}
];